name: Cargo Test

on:
  push:
    branches: 
      - "**"
  pull_request:
    branches:
      - "**"

# Make sure CI fails on all warnings
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run cargo test
        run: cargo test
